
const {Post} = require('../models');

const postData = [
    {
        author_id:5,
        content: 'Sloths are a group of arboreal Neotropical xenarthran mammals, constituting the suborder Folivora. Noted for their slowness of movement, they spend most of their lives hanging upside down in the trees of the tropical rainforests of South America and Central America. They are considered to be most closely related to anteaters, together making up the xenarthran order Pilosa. There are six extant sloth species in two genera Bradypus (three-toed sloths) and Choloepus (two-toed sloths). Despite this traditional naming, all sloths actually have three toes on each rear limb, although two-toed sloths have only two digits on each forelimb.[3] The two groups of sloths are from different, distantly related families, and are thought to have evolved their morphology via parallel evolution from terrestrial ancestors. Besides the extant species, many species of ground sloths ranging up to the size of elephants (like Megatherium) inhabited both North and South America during the Pleistocene Epoch. However, they became extinct during the Quaternary extinction event around 12,000 years ago, together with most large bodied animals in the New World. The extinction correlates in time with the arrival of humans, but climate change has also been suggested to have contributed. Members of an endemic radiation of Caribbean sloths formerly lived in the Greater Antilles. They included both ground and arboreal forms which became extinct after humans settled the archipelago in the mid-Holocene, around 6,000 years ago. Sloths are so named because of their very low metabolism and deliberate movements. Sloth, related to slow, literally means "laziness," and their common names in several other languages (e.g. French paresseux) also mean "lazy" or similar. Their slowness permits their low-energy diet of leaves and avoids detection by predatory hawks and cats that hunt by sight.[3] Sloths are almost helpless on the ground, but are able to swim.[4] The shaggy coat has grooved hair that is host to symbiotic green algae which camouflage the animal in the trees and provide it nutrients. The algae also nourish sloth moths, some species of which exist solely on sloths.',
    },
    {
        author_id:5,
        content: 'Bees are insects with wings closely related to wasps and ants, known for their role in pollination and, in the case of the best-known bee species, the western honey bee, for producing honey. Bees are a monophyletic lineage within the superfamily Apoidea. They are presently considered a clade, called Anthophila. There are over 16,000 known species of bees in seven recognized biological families.[1][2] Some species including honey bees, bumblebees, and stingless bees live socially in colonies while most species (>90%) including mason bees, carpenter bees, leafcutter bees, and sweat bees are solitary. Bees are found on every continent except for Antarctica, in every habitat on the planet that contains insect-pollinated flowering plants. The most common bees in the Northern Hemisphere are the Halictidae, or sweat bees, but they are small and often mistaken for wasps or flies. Bees range in size from tiny stingless bee species, whose workers are less than 2 millimetres (0.08 in) long,[3] to Megachile pluto, the largest species of leafcutter bee, whose females can attain a length of 39 millimetres (1.54 in). Bees feed on nectar and pollen, the former primarily as an energy source and the latter primarily for protein and other nutrients. Most pollen is used as food for their larvae. Vertebrate predators of bees include primates and birds such as bee-eaters; insect predators include beewolves and dragonflies. Bee pollination is important both ecologically and commercially, and the decline in wild bees has increased the value of pollination by commercially managed hives of honey bees. The analysis of 353 wild bee and hoverfly species across Britain from 1980 to 2013 found the insects have been lost from a quarter of the places they inhabited in 1980. Human beekeeping or apiculture (meliponiculture for stingless bees) has been practised for millennia, since at least the times of Ancient Egypt and Ancient Greece. Bees have appeared in mythology and folklore, through all phases of art and literature from ancient times to the present day, although primarily focused in the Northern Hemisphere where beekeeping is far more common. In Mesoamerica, the Mayans have practiced large-scale intensive meliponiculture since pre-Columbian times.',
    },

]

const seedPosts = () => Post.bulkCreate(postData);

module.exports = seedPosts;